### ISSUE TITLE
Просьба помочь

### ISSUE THREAD

**Issue by egorzot** [bitrix-expert/bitrix_boilerplate#10]
Допилил в [своей ветке](https://github.com/egorzot/bitrix_boilerplate) некоторые моменты:

- сделал выбор редакции
- сделал CentOS7
- сделал bitrix_env последней(бета) версии с MariaDB  ~~и куртизанками~~
- пофиксил пути при инициализации джедая

Нужен совет: выбор редакции сделан через отдельный sh скрипт, который запускается на родительской (хостовой) машине и жестко прописывает редакцию в файл /vagrant.custom/init.bash. Плюс это происходит при каждом запуске, т.е. при исполнении vagrant up тоже просит выбрать редакцию (хотя это ни на что не влияет). Считаю это все костылем, но до другого не дадумался, так как опыта с вагрантом мало. 
@may-cat есть идеи как это правильно реализовать?

**Comment by may-cat** [comment]
Спасибо большое за доработку :)
В идеале - нужно докинуть параметр при вызове vagrant up. Например, `vagrant up -edition=standart`
Я такое видел, вся фишка в том, что vagrantfile - это Ruby.

Альтернативный вариант - это задавать редакцию в переменной в vagrantfile. Самое топорное решение - завести пачку инсталл-скриптов, типа:
```
installstandart.sh
installstart.sh
...
```
и в вагрантфайле просто прописывать вызов нужного инсталла.
@egorzot
